/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import BBContractAbis from "./contractABIs";
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

/**
 * 手动添加已部署的合约信息
 */
const deployedContracts = {
  31337: {
    BBGameMain: {
      address: "0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9",
      abi: BBContractAbis.BBGameMain.abi,
    },
    BBGameHistory: {
      address: "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512",
      abi: BBContractAbis.BBGameHistory.abi,
    },
    BBRandomnessManager: {
      address: "0x8A791620dd6260079BF849Dc5567aDC3F2FdC318",
      abi: BBContractAbis.BBRandomnessManager.abi,
    },
    BBRoomCardNFT: {
      address: "0xB7f8BC63BbcaD18155201308C8f3540b07f84F5e",
      abi: BBContractAbis.BBRoomCardNFT.abi,
    },
    BBRoomLevelNFT: {
      address: "0x0DCd1Bf9A1b36cE34237eEaFef220932846BCD82",
      abi: BBContractAbis.BBRoomLevelNFT.abi,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
